# Generated by Django 3.1.1 on 2020-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='nu_rooms',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.IntegerField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='listing_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
