# Generated by Django 3.1.1 on 2020-12-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20201215_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='nu_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
