# Generated by Django 3.1.1 on 2020-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_auto_20201215_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='nu_rooms',
            field=models.DecimalField(decimal_places=1, max_digits=9, null=True),
        ),
    ]
