# Generated by Django 3.1.1 on 2020-12-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_auto_20201217_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_type', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='real_estate.listingtype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='real_estate.region'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='real_estate.saletype'),
        ),
    ]
